# --------------
# -- Settings --
# --------------

# Ignore this. This is only if you're hosting this in a sub-folder.
# If you're using GitHub pages, they automatically override this with the right value.
baseurl: ""

# If you're using GitHub pages without a custom domain, this is "https://[github username].github.io"
# If you're using GitHub pages with a custom domain, this is "http://[your domain]" (or https if you're using SSL)
url: "https://hackthepack.github.io"

# The ability to use custom themes.
style:
  theme: "original"

# This will help you track who's visiting your website.
tracking:
  google_analytics: "UA-114486187-1"

# Let people connect & engage with you through social media.
social:
  facebook_username: hackthepack2018

# This is Search Engine Optimization. It'll help your website look better on search.
seo:
  title:       "Hack the Pack | 7/8 April 2018"
  description: "This is the website for Hack the Pack at Northeastern University, April 7/8 2018."
  image:       "https://prime.mlh.io/img/logos/mlh-prime-color.svg"

# Event information.
event:
  name:        "Hack the Pack"
  description: "This is the website for Hack the Pack at Northeastern University, April 7/8 2018."
  date:        "7 & 8 April 2018"
  location:    "Boston, MA, United States"

  trust_badge:
    year:   "2018"  # season year
    region: "na"    # "na" or "eu"
    color:  "white" # "white", "black", "gray", "red", "blue" or "yellow"

  hero:
    links:
      - text: "Apply"
        my_mlh:
          client_id:    "837298bcc013372e89f4af4f8fe2901ed6c2c8d09edcc4743b9cbb08a0b11e83"
          redirect_uri: "https://hackthepack.github.io/success.html"
      - text: "Sponsor"
        href: "mailto:hackthepack2018@gmail.com"

  about:
    description: >
      A 24 hour student run hackathon at Northeastern University in Boston, MA. April 7-8 2018.

  # Info Sections
  info:
    sections:
      - image: "images/image1.png"
        title: "LEARN."
        description: >
          Use a new language or piece of hardware to learn something new.
      - image: "images/image2.png"
        title: "BUILD."
        description: >
          Build a cool project or just something that's been on your list.
      - image: "images/image3.png"
        title: "SHARE."
        description: >
          Present your project and show off what you've done!

  # Frequently asked questions.
  faq:
    - question: "What is a hackathon?"
      answer: >
        A hackathon is an invention marathon. Students come together to build cool
        software & hardware hacks over 24-48 hours. It's [very beginner friendly](https://medium.com/@tfogo/hackathons-are-for-beginners-77a9c9c0e000#.cj21niskl).
    - question: "How much does it cost?"
      answer: >
        Nothing. Attending a hackathon is free.
    - question: "Do I need to be a student to attend?"
      answer: >
        Yes. Only students who are currently enrolled at a Northeastern University are eligible to attend.
    - question: "Where is the event?"
      answer: >
        The event is being hosted at Northeastern University.
    - question: "What is Major League Hacking?"
      answer: >
        Major League Hacking is [the official student hackathon league](https://mlh.io) in North America & Europe.
        We work with over 200 Member Events and empower over 70,000 students every year.
    - question: "Is there a code of conduct?"
      answer: >
        Yes there is. We enforce it very strongly. You can [find it here](https://static.mlh.io/docs/mlh-code-of-conduct.pdf).

  # This is the message you'll receive once you've registered.
  register:
    message: >
      You'll receive more information closer to the hackathon.

# ----------------------------------------------------
# -- Ignore this unless you know what you're doing. --
# ----------------------------------------------------

markdown: kramdown
exclude:
 - node_modules
 - gulpfile.js
 - Gemfile
 - Gemfile.lock
 - package.json
 - README.md
 - CNAME
